version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
  backend:
    image: kv1o/foodgram:1.0
    restart: always
    depends_on:
      - db
    volumes:
      - static_data:/app/django_static/
      - media_data:/app/django_media/
    env_file:
      - ./.env
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../frontend/build/static:/var/html/static/
      - static_data:/var/html/django_static/static/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_data:/var/html/media/

volumes:
  postgres_data:
  static_data:
  media_data:
