# Generated by Django 3.0.5 on 2022-01-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220113_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='recipe',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='recipes.Recipe', verbose_name='Рецепт'),
            preserve_default=False,
        ),
    ]
