# Generated by Django 3.0.5 on 2022-01-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220114_1630'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='bookmark_unique'),
        ),
    ]
